### ISSUE TITLE
Integrate unit catalog and wiki

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#10]
- [ ] Copy the description directly in
- [ ] Catalog should provide links to the wiki pages

**Comment by AmoleR** [comment]
On this issue, would it be the wiki description goes into the catalog, or vice versa?

**Comment by vEnhance** [comment]
> On this issue, would it be the wiki description goes into the catalog, or vice versa?
Both

> Also it's worthwhile to note non-students can't access unit wiki pages. This should probably be changed.
Why so?

**Comment by AmoleR** [comment]
> Why so?
I accidentally mixed up catalog and syllabus for no explicable reason...whoops! I'll work on this PR in a bit.

**Comment by vEnhance** [comment]
>  I guess my question was where should this be edited, rather than where it's displayed.

For catalog -> wiki, maybe in the template for the catalog 

I'm not sure yet for the other direction.
