### ISSUE TITLE
List which handouts a problem appeared on

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#104]
In ARCH. This also requires work on Evan's local filesystem, extending the
upload-to-server script to give a list of handouts problem appeared in.

**Comment by Incompleteusern** [comment]
Is Von open source?

**Comment by vEnhance** [comment]
The database structure is but not the data itself.

https://github.com/vEnhance/von/

**Comment by Incompleteusern** [comment]
This might allow for reverse engineering the problems on units

**Comment by Incompleteusern** [comment]
I think this should be closed based off discussion in a discord thread.
