### ISSUE TITLE
Include walks in ARCH

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#109]
Requested by Arjun Gupta

**Comment by Incompleteusern** [comment]
Is there a script that takes in von tex files and creates the .html mentioned in source code?

**Comment by vEnhance** [comment]
OK wait I'm confused because I checked the script and it's already supposed to add walkthrough problems into the ARCH system.

e.g. I just checked that https://otis.evanchen.cc/arch/Z8C62ACE/ is in the system.

So I guess I'm gonna close LOL.
