### ISSUE TITLE
Missing commas in catalog

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#116]
![image](https://user-images.githubusercontent.com/3750940/202452401-8c9d01af-74ad-4baa-a28b-ec36442e42f9.png)

Should be an easy fix.

**Comment by Kd-Here** [comment]
Hey @vEnhance can I help you with this?

**Comment by vEnhance** [comment]
Yes! The 5 spades bounty and "good first issue" are there for a reason :)

**Comment by Elijah75** [comment]
Hey @vEnhance  Can you Help Me? I am Trying to Contribute For The First Time

**Comment by loki1205** [comment]
Hi, my name is Loknath Kumar Mishra, I would like to contribute. Can you please assign this to me?

**Comment by loki1205** [comment]
Thanks for assigning! Where and under what conditions can I reproduce the error. Can you guide me'

**Comment by vEnhance** [comment]
The screenshot should be pretty self-explanatory. Set up a local instance, put
in some test data in the django admin, and then go to the catalog page.

**Comment by vEnhance** [comment]
@Kd-Here @Elijah75 Wanted to mention I just opened #117 which is also a good intro/tutorial task

Might add some more as I think of them, since now I see there is some demand for some beginner quests :)

**Comment by lvj-dev** [comment]
Why can't I find where this thing is taken from? The thing
`otis-web/blob/main/core/templates/core/unitgroup_list.html`
has the structure but where is the actual 'list' of units?
Or don't you even need that?

**Comment by vEnhance** [comment]
> Why can't I find where this thing is taken from? The thing `otis-web/blob/main/core/templates/core/unitgroup_list.html` has the structure 

Hat's the template. Should be all you need. You want to tinker with line 36.

> but where is the actual 'list' of units? Or don't you even need that?

That's in the database, not the code. The model il `core/models.py`, class `Unit`.

BTW, I'm going to be doing a video stream on Wednesday night to try and make onboarding more straightforward. It's a lot to take in at once, I know.

**Comment by lvj-dev** [comment]
Bruh yeah. But, how does one see the changes one does to the site (before submitting a pull request or anything)?

**Comment by vEnhance** [comment]
> Bruh yeah. But, how does one see the changes one does to the site (before submitting a pull request or anything)?

https://www.djangoproject.com/start/ is probably what you want in terms of a text tutorial.

Alternatively, come to the stream on Wednesday, I'll be recording the entire clone procedure.

**Comment by vEnhance** [comment]
Oh, and https://github.com/vEnhance/otis-web/blob/main/README.md#standard-unix-environment of course :P

**Comment by lvj-dev** [comment]
Replying to this thing is fun. Sad I won't be able to come on Wednesday most probably. Last day of End of Year Exams on Thursday.

**Comment by vEnhance** [comment]
> Replying to this thing is fun. Sad I won't be able to come on Wednesday most probably. Last day of End of Year Exams on Thursday.

Well, the video will be recorded on twitch so you can watch the video whenever.

**Comment by lvj-dev** [comment]
Isn't a space between the unit names the most suitable option here?
For example,[
![sol](https://user-images.githubusercontent.com/116853849/203318943-7c907f1f-7320-4fc5-a265-dd2e991363bd.PNG)
](url)
