### ISSUE TITLE
Admin edit link from ARCH view

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#126]
**Describe the solution you'd like**
Admin edit link for ARCH on the hint list template. 

(More flexible than the website editor.)

**Comment by lvj-dev** [comment]
Wait what does this mean I don;t really understand.

**Comment by vEnhance** [comment]
On the page where the list of hints are displayed, under the link that says
"edit problem" there should be a link for admins that takes an admin to the
/admin page for that problem, where some more operations are possible (e.g.
deleting the problem).

**Comment by vEnhance** [comment]
> how are the problems on the arch hints put there i dont see a way?

I'm not sure what the question is. The SQL database is _not_ automatically
prepopulated, if that's what you're asking. Problems get added into the SQL
database by users interacting with the website, over time.

> plus whats with the url format in otis code for example
> `{% url "problem-update" problem.puid %}`

That's not a question, but basically that's just how the URL template tag works.
You should compare `arch/urls.py` to `{% url ... %}` invocations in other
templates, or read the documentation:

https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#url

> one last question where is the code for the admin part of the site
> that is for the GM Panel stuff

Admin is auto-generated, that's the point :) see `arch/admin.py`.

**Comment by lvj-dev** [comment]
> The SQL database is not automatically prepopulated, if that's what you're asking
like now when i create a problem on the admin view (arch) it doesn't have an option to like upload the problem statement

**Comment by vEnhance** [comment]
Those are read from a disk filesystem that you don't have access to.
Relevant method is `def get_disk_statement_from_puid(puid: str) -> Optional[str]:`.

You can just ignore this.

**Comment by lvj-dev** [comment]
I have such a knack at asking stupid questions but how do we redirect to the admin pages like does it even have a proper URL or smthn??

**Comment by vEnhance** [comment]
Yeah look in sidebar.html for an example
-- 
*Evan Chen (陳誼廷) *[via evanchen at mit.edu]
https://web.evanchen.cc/

**Comment by vEnhance** [comment]
Finished in b052af330b6524a01fe35381d8d977ab46e54a93.
