### ISSUE TITLE
Change "add hint" button color

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#127]
Change add hint button to green (primary ~> success).

Beginner friendly task since it involves changing like one line of code).

**Comment by Benneth-Paredis** [comment]
where is the add hint button situated on the site?

**Comment by vEnhance** [comment]
I think it’s the hint_list.html template? On mobile so can’t check easily.

You can also just search the repository for the string “Add hint”, eg `grep
“Add hint” -R **.html` from project root directory. In general that’s how I
find things in other people’s code, haha.
-- 
*Evan Chen (陳誼廷) *[via evanchen at mit.edu]
https://web.evanchen.cc/

**Comment by vEnhance** [comment]
Closed by #130
