### ISSUE TITLE
Bring roster/views.py coverage up to > 95%

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#134]
Lots of tests that need to be written and aren't lol

**Comment by Incompleteusern** [comment]
What is coverage?

**Comment by vEnhance** [comment]
> What is coverage?

Code coverage is a measure of how much of your code is at least _run_ by the testing suite. It's one way to get a rough pulse on how complete your test cases are.

This project uses https://coverage.readthedocs.io/en/7.0.5/ to measure code coverage.
