### ISSUE TITLE
Alum profiles

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#140]
I'd like a system that lets me keep track of what colleges all my kids went to
and whether they attended IMO/MOP/etc.

**Comment by lvj-dev** [comment]
Now why on earth would Evan want that? Bruh this sounds so like our vice principal.

**Comment by vEnhance** [comment]
It's kinda awkward to run into the alums and not even know what school they went to

**Comment by vEnhance** [comment]
Closing this because I got some feedback that people would feel uncomfy answering an alum survey
