### ISSUE TITLE
Allow unit petitions to lock a unit but not drop it

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#141]
Equivalent to "DROP" followed by "ADD FOR LATER" , but I guess this can be considered a quality-of-life feature or something.

Note that these should be gated by the same rules that "DROP" petitions are.

**Comment by lvj-dev** [comment]
I think the whole point is to stop these requiring confirmation. Like why on earth do we need confirmation for dropping a unit or locking it?

**Comment by vEnhance** [comment]
> I think the whole point is to stop these requiring confirmation. Like why on earth do we need confirmation for dropping a unit or locking it?

People abused them in past by requesting 9 units, downloading them and immediately dropping all 9 to request 9 more

**Comment by lvj-dev** [comment]
But ig no need of any confirmation for locking a unit or do you need?

**Comment by vEnhance** [comment]
still needs confirmation to lock for the same reason that drop needed confirmation

**Comment by lvj-dev** [comment]
So when u lock a unit u get a unit unlocked in place of it?
If so, why don't we make it so that the locking and unlocking confirmation comes in one (to make stuff faster)?

**Comment by RadialFunc** [comment]
working on this.

**Comment by Incompleteusern** [comment]
Should be closed by #155
