### ISSUE TITLE
Short poems describing each RPG level 

### ISSUE THREAD

**Issue by Novus-Stellachan** [vEnhance/otis-web#143]
Since from like level 72 onwards the level names get fantasy based and stuff, we could write cool poems describing each level. For example level 79 is Necromancer and you could have a poem like:

Through your eternal sleep he creeps,
On your heart his mark he leaves;
Seeping dark into your veins
His call shall permeate your grave.

You can't hide, and you can't run
Not from the Necromancer, not when he's done.

Of course, we don't have to restrict ourselves only to level 72 onwards, it's possible to write short poems for the earlier levels as well. As for who writes the poems, it could be like everyone interested can submit poems for each level and then the OTIS overlord could see which poem is the best. Maybe there could be this new button called "Lore" between the Submit Unit and Past Work which takes to a page containing the poem. 

Note: Doing this on the wiki would actually be pretty cool; but the wiki is publicly available and people would know the names of levels they have not yet reached; would feel like a major spoiler.

**Comment by vEnhance** [comment]
Yeah, I think this would be fun :)

I think ignoring the details of how to pick the poem for now, we should start by 
adding a `TextField onto the `Level` model in the RPG. (Trying to pull it from 
the Wiki sounds like a huge technical annoyance.)

**Comment by Incompleteusern** [comment]
I think it might be better to generalize from a poem to just snippets of words, kind of like the alt-text of xkcd images if you know what that is

**Comment by Novus-Stellachan** [comment]
Oooh, that sounds fascinating. Poems are difficult to come by (especially
on a fixed topic), and snippets also give a lot of freedom to presentation
and what not. And no, I did not know what alt-text of xkcd images. But a
few google searches later, and I understand what you mean. Sounds fine to
me.
