### ISSUE TITLE
Set date cutoff for 2nd sem

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#145]
Right now, when I approve a student registration application, it creates a new
invoice for the student with 2 semesters worth on it.

It would be better if the RegistrationContainer or Semester had a date on it
after which the 2 is 1 instead. Right now I just have to remember to manually
change it to 1 every time I add a new student after December or so, which is
annoying and error-prone (I have forgotten before and that causes a lot of
confusion with the parents).

The date would only need to be editable from admin interface, so this should be
easy. Create one new field, and add a few lines in `roster/admin.py`.

**Comment by Incompleteusern** [comment]
`registration/admin.py` seems to be a mistyping of `roster/admin.py`

**Comment by vEnhance** [comment]
> `registration/admin.py` seems to be a mistyping of `roster/admin.py`

Oops, yes, you're right.

**Comment by vEnhance** [comment]
Accidentally closed #146 instead of this oops
