### ISSUE TITLE
Better one-sem invoice logic

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#146]
The current system is super janky and doesn't quite do the right thing if
someone joins for only the spring semester.

**Comment by vEnhance** [comment]
9 spades should be awarded now!

**Comment by vEnhance** [comment]
to elaborate:

i think basically rn if you join for the 2nd semester then the system gets super confused
and thinks you haven't paid for the 1st semester
or smth silly like that
and it would be nice to make the logic correct

**Comment by Incompleteusern** [comment]
I think the issue is that
```python
            else:
                hours_taught = 0
            invoice = Invoice(
                student=student, preps_taught=n, hours_taught=hours_taught
            )
            first_payment_deadline = student.semester.first_payment_deadline
            if first_payment_deadline is not None and first_payment_deadline <= (
                grace_deadline := timezone.now() + timedelta(days=7)
            ):
                invoice.forgive_date = grace_deadline
```

`first_payment_deadline` is set but `most_payment_deadline` is not, so the `most_payment_deadline` gets flagged

**Comment by Incompleteusern** [comment]
Actually the issue is that `grace_deadline` is completely ignored by the rendering
