### ISSUE TITLE
Suggestion queue

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#153]
Apparently people like watching the backlog move, so if someone wants to
implement a queue for suggestions like with the problem sets, that might be a
welcome addition.

And then maybe I'll have more motivation to not let the suggestions just sit
there for months on end, LOL. (Especially now there are LaTeX requirements,
which should make the process much much smoother on my end.)

**Comment by Incompleteusern** [comment]
Going to start working on this
