### ISSUE TITLE
Unit submission comments

### ISSUE THREAD

**Issue by anterick-cjx** [vEnhance/otis-web#187]
Make it a feature to be a able to see Evan's comments on your unit submissions directly on your submission page in OTIS 

Another idea; what if there was an "inbox" inside of OTIS that basically consists of "notifications" with things like Evan's comments on your psets or notifications that your pset has been graded, etc.

**Comment by Incompleteusern** [comment]
> Another idea; what if there was an "inbox" inside of OTIS that basically consists of "notifications" with things like Evan's comments on your psets or notifications that your pset has been graded, etc.

This can be done through the bootstrap notification system I think?

**Comment by Incompleteusern** [comment]
This can probably be done through integration with https://github.com/vEnhance/dotfiles/blob/main/venueQ/otis.py
