### ISSUE TITLE
DJLint Consistently fails

### ISSUE THREAD

**Issue by AmoleR** [vEnhance/otis-web#191]
**Describe the bug**
DJLint is so insistent on the string being indented even more.

**To Reproduce**
Run `djlint . --check` and check `payments/templates/payments/jobfolder_list.html`.

**Expected behavior**
It doesn't try to error out. Because what?

**Screenshots**
[Video](https://cdn.discordapp.com/attachments/743594303338578032/1082504144952242256/Screen_Recording_2023-03-06_at_7.24.29_PM.mov)

Also it would be great to figure out why DJLint doesn't respect indenting by 2 spaces and is insistent on 4.
- [ ] Fix DJLint's string indenting, possibly by commenting it out (I don't know how).
- [ ] Fix DJLint's indentation errors.

**Comment by Incompleteusern** [comment]
I still think that it simply indented the entire lambda the first time, and then indented just `let item =` the second time

**Comment by Incompleteusern** [comment]
wait no im going crazy nvm

**Comment by christopherpickering** [comment]
@AmoleR can you link to the code snippet that is failing?

**Comment by vEnhance** [comment]
@christopherpickering here's a minimal example that produces the issue:

```html
<script type="text/javascript">
  let s = `
    <p>
        Text.
    </p>`;
</script>
```

I was able to reproduce the issue with `djlint --reformat --format-js snippet.html` on 1.19.12, which repeatedly indents the string.
```
I /tmp >> djlint --version                                                               [11:12]
djlint, version 1.19.12
I /tmp >> cat snippet.html                                                               [11:12]
<script type="text/javascript">
  let s = `
    <p>
        Text.
    </p>`;
</script>
I /tmp >> djlint --reformat --format-js snippet.html                                     [11:12]

Reformatting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00    


tmp/snippet.html
───────────────────────────────────────────────────────────────────────────────────────────────
@@ -1,6 +1,4 @@

 <script type="text/javascript">
-  let s = `
-    <p>
-        Text.
-    </p>`;
+    let s = `
+        <p>Text.</p>`;
 </script>

1 file was updated.

I /tmp [1] >> djlint --reformat --format-js snippet.html                                 [11:12]

Reformatting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00    


tmp/snippet.html
───────────────────────────────────────────────────────────────────────────────────────────────
@@ -1,4 +1,4 @@

 <script type="text/javascript">
     let s = `
-        <p>Text.</p>`;
+            <p>Text.</p>`;
 </script>

1 file was updated.
```

![image](https://user-images.githubusercontent.com/3750940/234365010-8bd0c736-74ef-4fdd-bda2-1fbf49ba8700.png)

**Comment by vEnhance** [comment]
@christopherpickering if there's a place upstream where it'd be helpful for me to report this, just let me know and I can do so.

**Comment by christopherpickering** [comment]
@vEnhance https://github.com/Riverside-Healthcare/djLint/issues
Thanks for the example!

**Comment by Incompleteusern** [comment]
This seems to have bene fixed in the latest djlint?

**Comment by vEnhance** [comment]
Yeah, I can close.
