### ISSUE TITLE
Duplicated Submission Messages

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#196]
**Describe the bug**

**To Reproduce**

Spam https://otis.evanchen.cc/markets/guess/finaid-viii/ while already having a submitted answer.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/58920010/224523461-9814cf96-a54b-4d89-8bb3-2c6d6092bf49.png)

A bunch of "You already submitted" messages pop up

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox Nightly
- Version 112.0a1+20230311.1+h0565e88d9452-1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AmoleR** [comment]
Easiest thing to do is unobtrusive JS client side. Example is:

```js
$("form").submit(function () {
    if ($(this).valid()) {
        $(this).submit(function () {
            return false;
        });
        return true;
    }
    else {
        return false;
    }
});
```

Only thing to change is `form` to something else as necessary.

**Comment by AmoleR** [comment]
Also note the above approach discards multiple submissions. If you want to only block submissions until you have a response received, you can simply just have a variable and await a response. Something like the following:

```js
let can_submit = true;

const on_submit = () => {
  if (!can_submit) return;
  can_submit = false;

  const request = await fetch('blargh', {
    method: 'POST'
  });
  const data = await request.json();
  can_submit = true;
}
```

**Comment by Incompleteusern** [comment]
I think the issue occurs even as a GET request

**Comment by AmoleR** [comment]
> I think the issue occurs even as a GET request

Type of request doesn't matter. This is just an example of using JS to get around the issue.

**Comment by Incompleteusern** [comment]
I don't think this fixes it since its run in `dispatch`, see https://github.com/vEnhance/otis-web/blob/f06949689f988b20b62d7eb1cc192cf999d8f369/markets/views.py#L69
```python
    def dispatch(
        self, request: HttpRequest, *args: Any, **kwargs: Any
    ) -> HttpResponseBase:
        self.market = get_object_or_404(Market, slug=kwargs.pop("slug"))
        if not isinstance(request.user, User):
            return super().dispatch(request, *args, **kwargs)  # login required mixin

        if not self.market.has_started:
            return HttpResponseNotFound()
        elif self.market.has_ended:
            return HttpResponseRedirect(self.market.get_absolute_url())
        try:
            guess = Guess.objects.get(market=self.market, user=request.user)
        except Guess.DoesNotExist:
            pass
        else:
            messages.error(
                request, f"You already submitted {guess.value} for this market."
            )
            target_url = reverse("market-pending", args=(guess.pk,))
            return HttpResponseRedirect(target_url)

        return super().dispatch(request, *args, **kwargs)
```
