### ISSUE TITLE
Unit AK Spade Values

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#199]
I hate addition so much, it would be nice to have a way for each unit to show how many clubs you should get if you do every single problem.

**Comment by Incompleteusern** [comment]
See https://github.com/vEnhance/dotfiles/blob/48cd6866532e2dd18c6775b104e39f162976ae0c/venueQ/otis.py for reference on how to find total club sums

**Comment by vEnhance** [comment]
tbh i think editing `otis.sty` would be the easiest way to accomplish this, if you want the result to actually show up in the unit PDF

seems annoying though

**Comment by Incompleteusern** [comment]
You could probably declare a global sum variable with pythontex, then each of
```tex
    \newcommand{\vonE}{\renewcommand{\vonenvname}{probE}\von}
    \newcommand{\vonM}{\renewcommand{\vonenvname}{probM}\von}
    ...
``
could add to the variable ig

**Comment by vEnhance** [comment]
I'd rather use native `\newcounter` and `\addtocounter` rather than muck around more with pythontex, it's clunky enough as is.

Then `\conclusion` could be edited to print the total.

**Comment by Incompleteusern** [comment]
Oh, lol
