### ISSUE TITLE
Catalog as a Checklist?

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#206]
https://otis.evanchen.cc/core/catalog/ could color complete units into a different color.

Something like this
![image](https://user-images.githubusercontent.com/58920010/231849911-a42aecbb-3912-4a1f-88a0-d2d9c75ecded.png)

**Comment by vEnhance** [comment]
Seems like a reasonable feature suggestion.

**Comment by Incompleteusern** [comment]
Going to note that this is partially completed with a checkmark, but the granular level of versions of units is not done

**Comment by jatloe** [comment]
A small extension: Using a third color for units that you AK?

**Comment by vEnhance** [comment]
server doesn't have a way of knowing whether you AK'd a unit because the materials stuff is all done on my machine (so e.g. server doesn't know what problems are on each unit or how much they're worth, it just has the pdf handout)

**Comment by Incompleteusern** [comment]
You can AK all units except for like secret units and any other unit with <= 2 problems iirc.

**Comment by vEnhance** [comment]
Right but the point is the server doesn't know _whether_ you AK'ed the unit, 
because it doesn't know the total clubs in the unit (which keeps changing over 
time), hence can't compare it to the number of clubs claimed.

You'd need a Boolean flag on each pset submission or something.
