### ISSUE TITLE
need to log in to create new problems

### ISSUE THREAD

**Issue by cinnamonroarz** [vEnhance/otis-web#228]
When you are logged in to otis and click on arch link to a nonexistent problem that is the database it says that you must be logged in to create new problems, but you already logged in.

**To Reproduce**

1. Log in to otis
2. Go to https://otis.evanchen.cc/arch/17HMMTC7
3. It will say that you must be logged in to create new problems

**Screenshots**
<img width="862" alt="image" src="https://github.com/vEnhance/otis-web/assets/135482109/78f854d7-576f-47e8-836e-4a979772ee8f">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: vivaldi
- Version: 6.1.3035.111

**Comment by jatloe** [comment]
Can't replicate on Chrome + Windows 10, maybe try logging out and back in / clearing cookies?

**Comment by cinnamonroarz** [comment]
Nope, doesn't work. This happens on Microsoft Edge too.

**Comment by jatloe** [comment]
Are you still using the 17HMMTC7 link on Edge? I guess it's not a nonexistent problem anymore and I used that link to test.

**Comment by cinnamonroarz** [comment]
ECV11118 is a currently nonexistent problem now.

**Comment by cinnamonroarz** [comment]
oh wait it's fixed now sorry

**Comment by cinnamonroarz** [comment]
wait this issue still occurs for 18HMMTC9
