### ISSUE TITLE
Drop Petitions Automatically

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#230]
I don't see reason why this can't be done.

**Comment by vEnhance** [comment]
i explained the reason in #240 before, see https://github.com/vEnhance/otis-web/issues/141#issuecomment-1336431646

> People abused them in past by requesting 9 units, downloading them and immediately dropping all 9 to request 9 more

therefore i decided i want to manually review the drop requests as well to make sure they are reasonable and not just mass dropping newly obtained units for seemingly no reason

**Comment by Incompleteusern** [comment]
My thinking was that the "immediately requesting 9 more units" could be detected.

**Comment by vEnhance** [comment]
on my end it's easier to detect abnormal drop requests than abnormal unlock requests
