### ISSUE TITLE
Subject color in the units page is overridden by the striped gray thing

### ISSUE THREAD

**Issue by jatloe** [vEnhance/otis-web#231]
This is probably intended but it does make it annoying to see which unit is which subject at a glance
![image](https://github.com/vEnhance/otis-web/assets/85522239/f521bc2b-942f-4210-92c3-cfe36ad016f8)

**Comment by vEnhance** [comment]
that's definitely a bug it's supposed to be gray for locked

**Comment by vEnhance** [comment]
should be fixed in ed3c912b5461906a2fd88b5bda66590008c2d332

**Comment by jatloe** [comment]
yay
