### ISSUE TITLE
Rename "Request Units"

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#234]
![image](https://github.com/vEnhance/otis-web/assets/58920010/e2fb0bd9-12b5-4fba-ba47-75e42200b0f0)

Kinda misleading since it also locks, drops, and add for laters units.

**Comment by vEnhance** [comment]
lol did you put the wrong image

suggestions for better names are welcome

**Comment by Incompleteusern** [comment]
"Modify units" and "Manage units" both work. There's also an argument for moving "Submit units" next to this button ig.

**Comment by vEnhance** [comment]
how aboout "request changes to units"

**Comment by Incompleteusern** [comment]
Idk, a bit long tho

**Comment by jatloe** [comment]
I like "manage units"

**Comment by vEnhance** [comment]
OK i'll do "manage units"
