### ISSUE TITLE
write tests for get_news

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#236]
need to write this later, but prioritizing getting this onto prod because kickoff is going out tonight and i literally just thought of this feature like 40 minutes ago so hahaha

tbh i bet `dismiss` isn't tested at all right now either smh

secretly hoping someone writes this for me but expecting it to be more like, i eventually force myself to do this once otis stuff dies down a bit

**Comment by Incompleteusern** [comment]
Calling dibs.
