### ISSUE TITLE
Cap hint% at 100%

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#237]

**Comment by vEnhance** [comment]
dang that means i have to fix all the 1434% hints manually q_q

probably should have put that validator in beforehand huh

**Comment by jatloe** [comment]
Are we closing this (due to alternative hints)?

**Comment by vEnhance** [comment]
i guess so

(for context: some people are using > 100 numbers to indicate hints that move along different solution paths)
