### ISSUE TITLE
Allow resubmissions of units from previous years.

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#240]

**Comment by vEnhance** [comment]
what's the current behavior?

**Comment by Incompleteusern** [comment]
I think I (or maybe you) authored a commit to disable resubmissions on inactive submissions (didn't work well with everything else). 

There's a fair chance that its infeasible to integrate this without actually adding the unit to the current curriculum, but idk.

**Comment by vEnhance** [comment]
OK I think the procedure should be that you submit it fresh on the new account, but there's a bug right now where it counts the unit twice when tallying your stats

So we should fix it to take the maximum instead across all appearances of a unit.

**Comment by Incompleteusern** [comment]
Units a person had in previous years could just be automatically unlocked in unit petition. That might be the cleanest way.

**Comment by vEnhance** [comment]
With the repeat-submit-unit bug fixed in 6ff81e14046cd3468f998a7036acc433fc9d7a71, I think this should be essentially handled. Maybe the only thing is that we should also do

> Units a person had in previous years could just be automatically unlocked in unit petition. That might be the cleanest way.

but maybe that should be a separate issue if people want it.
