### ISSUE TITLE
Allow inactive students to edit forged diamonds

### ISSUE THREAD

**Issue by DottedCalculator** [vEnhance/otis-web#241]
Going to https://otis.evanchen.cc/rpg/forge/ID/ for some inactive student gives a 403 error.

**Comment by Incompleteusern** [comment]
This is added intentionally by https://github.com/vEnhance/otis-web/blob/787c3353dec1fcfeee8f555e472db8fa7325af84/rpg/views.py#L367, though it is noteworthy that this code originates from over two years ago.
