### ISSUE TITLE
The club symbol looks really different aesthetically in terms of size etc

### ISSUE THREAD

**Issue by jatloe** [vEnhance/otis-web#243]
![image](https://github.com/vEnhance/otis-web/assets/85522239/30796d1e-1fb4-4b5c-8344-3a0e64526eea)

**Comment by jatloe** [comment]
How do I change the label? It's more of a polish but I can't change it

**Comment by Incompleteusern** [comment]
![image](https://github.com/vEnhance/otis-web/assets/58920010/255aba36-4c7a-4fad-b602-97d018ad1290)
This results from the fact that emojis in otis-web are resolved by the client.

**Comment by vEnhance** [comment]
closing since iirc there's nothing we can do about this as the user browser renders the emoji

unless someone wants to make images for me (or twemoji?), ha

**Comment by jatloe** [comment]
Can we just change this instance by overriding the club emoji only on chrome then?

**Comment by Incompleteusern** [comment]
That's still nontrivial but still possible, https://stackoverflow.com/questions/39875299/how-to-use-an-emoji-font-on-a-website

**Comment by jatloe** [comment]
can we reopen this?

**Comment by Incompleteusern** [comment]
You should be able to do so, and we could use `twemoji` to do so lol (soon to be renamed xmoji).

**Comment by vEnhance** [comment]
if someone gets twemoji to work please submit a PR

**Comment by jatloe** [comment]
speaking of emojis being weird, the light bulb being not centered makes me very sad
![image](https://github.com/vEnhance/otis-web/assets/85522239/080466ce-446b-4318-9add-cb7b6a52be75)
