### ISSUE TITLE
In test data, there is no running year to test submitting units etc

### ISSUE THREAD

**Issue by jatloe** [vEnhance/otis-web#244]
Or maybe there is and I'm supposed to run something? Not sure

**Comment by vEnhance** [comment]
I think `Year 2` should have `active=True` in the test data?

**Comment by jatloe** [comment]
it's inactive for me? idk
![image](https://github.com/vEnhance/otis-web/assets/85522239/2dff5924-2365-4e53-915a-fe216eedddef)
`git diff` doesn't reveal any differences

**Comment by Incompleteusern** [comment]
its active for me
![image](https://github.com/vEnhance/otis-web/assets/58920010/69cca73c-5682-4e2f-81db-8641270aa86a)

**Comment by jatloe** [comment]
still not active for me
do I need to run the load all or something?

**Comment by Incompleteusern** [comment]
Try regenerating your fixtures

**Comment by jatloe** [comment]
what does that mean

**Comment by jatloe** [comment]
works now
thanks
