### ISSUE TITLE
User groups are missing in fixtures

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#252]
For some reason the fixtures with dummy data don't put the generated users into `Verified` or `Active Staff` respectively. Need to find out why, regen the dummy data and then update the `all.json` fixtures file accordingly.

**Comment by Incompleteusern** [comment]
![image](https://github.com/vEnhance/otis-web/assets/58920010/72eda599-eefe-41a8-90c9-6c4177a26e8e)

The `@postgeneration` part is probably not ran by `fast_bulk_batch`
