### ISSUE TITLE
gray out "Solution (TeX)" button when there is no solution in database

### ISSUE THREAD

**Issue by jatloe** [vEnhance/otis-web#257]
![image](https://github.com/vEnhance/otis-web/assets/85522239/e54a71b1-8dbd-441d-9d8f-4aaee0b74c31)

**Comment by Incompleteusern** [comment]
This results since its a user made problem

**Comment by jatloe** [comment]
yeah but it's still fixable

**Comment by vEnhance** [comment]
i'll just hide the button altogether if there's no poblem statement
