### ISSUE TITLE
QoL features in https://otis.evanchen.cc/core/catalog/

### ISSUE THREAD

**Issue by jatloe** [vEnhance/otis-web#259]
- search function
- filtering by difficulty/subject
- a way to get to a specific subject(like in the outlines of a pdf)
- sort by something other than name

(I know that some of these features can be done by Ctrl+F but idk)

**Comment by Incompleteusern** [comment]
We already have a search function  filter by subject its called Ctrl-F. Furthermore, I think most of the time you want to do a unit, then choose difficulty, rather than vice versa.

**Comment by jatloe** [comment]
yeah ik all of these are small things but like
![image](https://github.com/vEnhance/otis-web/assets/85522239/20f1bda5-2bf9-470d-abb0-cbe5afd15fae)
is just annoying idk

**Comment by zvfrozel** [comment]
Cool, i wanted to open an issue saying the exact same thing.

In that case i shall just claim this task

**Comment by zvfrozel** [comment]
Fixed the issue at https://github.com/vEnhance/otis-web/pull/364

![image](https://github.com/user-attachments/assets/6eeacfc7-77fe-4740-ab04-0192016754c2)
