### ISSUE TITLE
Merge "manage units" and "request secret units" maybe?

### ISSUE THREAD

**Issue by jatloe** [vEnhance/otis-web#260]
idk it feels inconsistent
![image](https://github.com/vEnhance/otis-web/assets/85522239/196ad7d1-05a7-4a95-8478-e813b65a3179)

**Comment by Incompleteusern** [comment]
IMO this would lead to more code complexity. Furthermore, you don't actually really request secret units.

**Comment by jatloe** [comment]
i mean you do have to add it to your curriculum and unlock it and it counts as a slot tho

**Comment by vEnhance** [comment]
this feels like extra code complexity because the two functions are quite different on the backend
