### ISSUE TITLE
"TeX On" and "TeX Off" broken for Problem Suggestions

### ISSUE THREAD

**Issue by RyanLi1618** [vEnhance/otis-web#27]
The "TeX On" and "TeX Off" buttons don't appear to do anything when clicked when submitting a problem suggestion.

**Comment by AmoleR** [comment]
Looks like we know the issue:
<img width="431" alt="Screen Shot 2021-08-27 at 5 51 24 PM" src="https://user-images.githubusercontent.com/43121460/131200934-d66b6d53-15c7-4c23-8a80-49cb8a3fef96.png">
In [the Problem Suggestion Form](https://github.com/vEnhance/otis-web/blob/main/dashboard/templates/dashboard/problemsuggestion_form.html), the `MathJax.Hub.Queue` call is completely useless.

The [MathJax documentation of Queues](https://docs.mathjax.org/en/v1.1-latest/queues.html) surprisingly **tells** you to do what you did, so I'm not sure. I'll maybe check on it later.

**Comment by vEnhance** [comment]
Yeah, looks like it got borked by me upgrading MathJax, so I'll have to hash that out.

**Comment by vEnhance** [comment]
This is nice, thanks.

I'm going to make a few cosmetic edits to make the button a little less
confusing (by verb-ifying things), and then merge it.

**Comment by vEnhance** [comment]
Finished in 8a56b604375df296bde07fc5ab4cb07aee53112a.
