### ISSUE TITLE
Heads-up on upcoming events

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#271]
It would be nice if the markets page indicated when the next market was going to
open (by looking in the database for markets that haven't started and taking the
next one), without revealing any details about what would happen in the market.
Builds some hype, you know.

Similar for Hanabi seeds.

**Comment by vEnhance** [comment]
assigning to @waystern

**Comment by vEnhance** [comment]
to clarify i was imagining just like, on the list of markets/hanabi seeds, it shows at the top time until next one opens if there's none open atm

**Comment by waystern** [comment]
commenting so evan can assign

**Comment by vEnhance** [comment]
> commenting so evan can assign

done!

**Comment by vEnhance** [comment]
@waystern how's it going?

**Comment by waystern** [comment]
@vEnhance I'm finishing getting otis web setup locally on my computer.. I've been pretty busy with school but I'll have more time the next couple days and should be able to finish it (probably with some help) this weekend

**Comment by vEnhance** [comment]
congrats @waystern :)

it'll be live on prod in about 10 minutes if all goes well.
