### ISSUE TITLE
Horrifying red box when Hint Number Already Exists

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#278]
![image](https://github.com/vEnhance/otis-web/assets/58920010/df03864a-1a44-421d-9c54-4ea2f8650d86)

To recreate, make a hint at n% and a hint at n-1%, then edit the form to change n-1% to n%

**Comment by jatloe** [comment]
LOL

**Comment by jatloe** [comment]
![image](https://github.com/vEnhance/otis-web/assets/85522239/6edcc4b7-22a3-4626-8df4-bca5a887c20e)
larger screenshot
