### ISSUE TITLE
Too many units

### ISSUE THREAD

**Issue by chessisdabest** [vEnhance/otis-web#303]
**Describe the bug**
Too many units
**To Reproduce**

Get 9 units.
Complete a unit
Submit a drop request for that unit
Submit that unit anyways
Request another unit because that one got dropped (back to 9)
Recieve that unit, and the unit from submissiom. (10)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vEnhance** [comment]
Brilliant. I'll fix this now.

If you give me a student ID, I can give you a large spade bounty for catching 
this vulnerability, like I promised in syllabus appendix B.
