### ISSUE TITLE
What's the purpose of auto hold?

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#315]
```python
    # auto hold criteria
    num_psets = PSet.objects.filter(student=student).count()
    auto_hold_criteria = num_past_unlock_inquiries > (10 + 1.5 * num_psets**1.2)

    if auto_hold_criteria:
        inquiry.status = "INQ_HOLD"
        inquiry.save()
        logger.log(
            SUCCESS_LOG_LEVEL,
            f"Held {student}'s petition to {inquiry.action_type} {inquiry.unit} "
            f"({num_psets} psets and {num_past_unlock_inquiries} unlock petitions).",
            extra={"request": request},
        )
        messages.warning(
            request,
            "You have submitted an abnormally large number of petitions "
            + "so you should contact Evan specially to explain why.",
        )
        return
```

I can't really figure out this code's use case. If you've done enough units, nothing occurs. And I can think of perfectly legitimate reasons for having an abnormally high amount of unit unlocks (for example, accidentally getting too many hard units as a newbie), at which point this code.

**Comment by vEnhance** [comment]
> And I can think of perfectly legitimate reasons for having an abnormally high amount of unit unlocks (for example, accidentally getting too many hard units as a newbie), at which point this code.

Sure. But I can think of plenty of illegitimate reasons too. Like hoarding units.
The point is that if you are somehow above the (extremely generous) threshold, talk to me specifically.
