### ISSUE TITLE
Recent Waltz Quiz commit retroactively decreased my score

### ISSUE THREAD

**Issue by jatloe** [vEnhance/otis-web#329]
Commit: https://github.com/vEnhance/otis-web/commit/909aa4c521a7327ea1cbbadbc948a7c22d0a9e43

I submitted 150+sqrt((60*60*50+36*36*40-40*50*90)/90) to P2 in Waltz Quiz E and was marked correct; however, after the commit, my submission got retroactively marked incorrect.

I think the solution to this is to add a submit time check to the code so that anything submitted before the commit is still valid.

**Comment by vEnhance** [comment]
I had it in my head that scores are only computed at submission time.

**Comment by vEnhance** [comment]
jatloe I gave you your point back as well
