### ISSUE TITLE
uhh I can't submit a diamond anymore

### ISSUE THREAD

**Issue by jatloe** [vEnhance/otis-web#331]
![image](https://github.com/vEnhance/otis-web/assets/85522239/29ea8646-c829-4ce7-8cf3-460a09b8f9e9)

Can't submit digits

**Comment by jatloe** [comment]
nice `widget=forms.TextInput(attrs={"pattern": "[a-fA-F]+"}),`
lol
https://github.com/vEnhance/otis-web/commit/a586b1e55be75953f50ba92795d401229e9a26ee
@vEnhance

**Comment by Incompleteusern** [comment]
honestly seems like a skill issue

**Comment by jatloe** [comment]
nou >:( >:( >:(
