### ISSUE TITLE
Tex files not downloading instantly

### ISSUE THREAD

**Issue by chessisdabest** [vEnhance/otis-web#336]
**Describe the bug**
I cant download the tex templates.
**To Reproduce**
Just try to download it 

**Expected behavior**
Downloads a tex file like it used to

**Comment by vEnhance** [comment]
can't repro

**Comment by chessisdabest** [comment]
I got a screen recording

[screen-capture.webm](https://github.com/vEnhance/otis-web/assets/144521728/24658d06-1d7d-4d26-a56e-f117c6583f06)

**Comment by vEnhance** [comment]
This is the intended behavior, just press Ctrl-S to save.

See https://discord.com/channels/740366393022742618/808946189457293319/1195041688335417375 for accompanying discussion.

Closing as wontfix.
