### ISSUE TITLE
Toggle Lock in Unit viewing.

### ISSUE THREAD

**Issue by EzraG101** [vEnhance/otis-web#34]
Currently in the "Your Units" section of the site there are two buttons for toggling which units are visible. However, when you reload the site (for example, by clicking "View Stats" then coming back) the unit view defaults to showing all units. Perhaps there could be a setting that each User can set so that these toggles are locked. That is, so that when the site is reloaded, the unit viewing defaults to the user selected option (like not showing completed).

**Comment by vEnhance** [comment]
This is planned in #8.
