### ISSUE TITLE
Preview button doesn't work on Wiki

### ISSUE THREAD

**Issue by arulkolla** [vEnhance/otis-web#35]
When I try to preview changes on the wiki, it gives up and instead throws a bunch of console errors.
<img width="465" alt="Screen Shot 2021-08-30 at 4 56 49 PM" src="https://user-images.githubusercontent.com/52571202/131420507-0bc319eb-8d6f-480b-8af8-643eaf9e2820.png">

**Comment by AmoleR** [comment]
Oh god, this seems like an issue I probably created while fiddling around in MathJax to fix #27. Well, I guess I'll patch really quick.

**Comment by vEnhance** [comment]
@arulkolla can you check if this is fixed now

**Comment by arulkolla** [comment]
> @arulkolla can you check if this is fixed now

Oops I didn't see this; yeah it works now 🎉
