### ISSUE TITLE
The AOPS link 

### ISSUE THREAD

**Issue by itsbesi** [vEnhance/otis-web#358]
**Describe the bug**
The AOPS link isn't connected with the right problem.

**To Reproduce**

1. Go to 'AIME Mods' unit
2. Scroll down to the page 8 at the problem 24
3. The Aops link of P24  " AIME II , 2024 P7" is linked with the  "2024 AIME II P11" so that link is not correct.

**Screenshots**
![Screenshot 2024-08-16 220335](https://github.com/user-attachments/assets/d8999770-94f4-4869-b89b-e363fc079e4a)
![Screenshot 2024-08-16 220354](https://github.com/user-attachments/assets/2a14c54a-a4df-4488-b85b-b73a04ac2326)

**Comment by Incompleteusern** [comment]
This is not a software bug and shouldn't be reported here ideally, and #reqs-for-evan is a better place.

**Comment by itsbesi** [comment]
Oh alright, didn’t know where to report it sorry

**Comment by vEnhance** [comment]
Email is actually best for things like this. I hate tracking stuff with Discord.

I recompiled the file, so should work now.

**Comment by itsbesi** [comment]
Oh alright thanks alot.
I just love OTIS and it inspires me to build a simmlar website in the
future( not about math) so i reportd that part because thought would be
great to fix it.
Again thanks alot and sorry for not sending an email first
