### ISSUE TITLE
Separate Production Dependencies from Development Dependencies

### ISSUE THREAD

**Issue by AmoleR** [vEnhance/otis-web#36]
Trying to build my Dockerfile, but I keep getting:
```
ERROR: Could not build wheels for google-crc32c which use PEP 517 and cannot be installed directly
```
Maybe, as `google-crc32c` is **not** needed for core functionality but **is** needed for production, segregation of these should ideally occur?

**Comment by vEnhance** [comment]
i think we should be able to move the google thing to a separate dependency group

allauth might be trickier. how much grief does allauth give your dockerfile?

**Comment by AmoleR** [comment]
None; google is literally the only thing (I think) causing me to install 300,000 different things. I've already gotten the Dockerfile down other than Google's CRC32C.

**Comment by vEnhance** [comment]
wasn't `cryptography` causing grief or something? that seems to be required by `django-allauth`

**Comment by AmoleR** [comment]
Cryptography did cause some issues, but I ended up forcing it to download a pre-built version (I love you whoever made that an option).

**Comment by vEnhance** [comment]
is there a way i can force that so future developers don't have any grief

**Comment by AmoleR** [comment]
Yep, just set an environment variable:
```
CRYPTOGRAPHY_DONT_BUILD_RUST=1
```

**Comment by vEnhance** [comment]
amol can you pull the dephell branch from #38 and see if it works reasonably

**Comment by AmoleR** [comment]
Looks good!

**Comment by vEnhance** [comment]
Finished in 7e2ebe088348fe4b4ddb4e9b60adcfc3df99d436.
