### ISSUE TITLE
Hogwarts subject colour scheme (we have a Harry Potter inaccuracy)

### ISSUE THREAD

**Issue by zvfrozel** [vEnhance/otis-web#370]
The OTIS-WEB subject colours are currently not faithful to the Harry Potter colour scheme, which is clearly a massive issue:

![image](https://github.com/user-attachments/assets/5e41e314-cab9-485a-855a-29663e423968)

The current colour scheme has:
- Algebra and Func eqns. (Hufflepuff) - Red ❌
- Combi (Gryffindor) - Blue ❌
- Geo (Slytherin) - Green ✅
- NT (Ravenclaw) - Grey ❌

![image](https://github.com/user-attachments/assets/a7e5f310-4847-45b6-8194-3cd0cc66e407)

I propose changing Algebra to yellow, Combi to red, and NT to blue. The colour for Misc. can become grey.

Apart from the dashboard curriculum list, these colour schemes can be used universally across the website - e. g. on unit PDFs and the catalog

**Comment by jatloe** [comment]
#makegeored

**Comment by vEnhance** [comment]
This is pretty amusing :P Alas I've gotten so used to the color associations (having used them for 15 years or so, since I was a student) that I probably won't change them now.
