### ISSUE TITLE
Tooltips for emoji links

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#39]
For any `a.emoji-link` create a tooltip beneath it that shows the alt text of
the link.

**Comment by AmoleR** [comment]
The `title` prop on anchor tags should do this?

**Comment by vEnhance** [comment]
oh, is it `title` and not `alt` lol

Well, even then I think it's not that conspicuous, I'd prefer to hack my CSS version like I did for the stats at https://mosp.evanchen.cc/ than rely on the built-in ones

**Comment by vEnhance** [comment]
Finished in 487b4a4dcd1fea4191eab4f9f3ab8c98fd91f57f.
