### ISSUE TITLE
Alignment slightly off in dashboard icons

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#40]
https://discord.com/channels/740366393022742618/808946189457293319/882338099470950472

**Comment by Psi25Omega** [comment]
I think this issue is device specific. Coz the alignment is fine on the devices I use.

**Comment by AmoleR** [comment]
@Psi25Omega it's more likely browser-specific than device specific; use [playwright](https://playwright.dev) and you should be able to emulate Chromium (Edge and Chrome), Firefox, and Safari.

**Comment by Psi25Omega** [comment]
oh…I’ll look into it

**Comment by vEnhance** [comment]
Closing as WONTFIX due to lack of interest and perceived not-that-importantness.
