### ISSUE TITLE
Validate PUID on client side

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#42]
Javascript-only task. Modify `arch/problem_form.html` so that if `#id_puid` does
not match the regular expression `[0-9A-Z]+` it warns the user and prevents them
from submitting the form. This mirrors the analogous validation done on the
server side but improves UX since the feedback is faster.

**Comment by TheCoolDinosuar** [comment]
I call dibs on this one

**Comment by vEnhance** [comment]
Would be better in fact if it also auto-capitalized the field, I think.
