### ISSUE TITLE
Recent emails aren't sorted in order

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#45]
also I thought I asked for only the last 2 weeks worth of announcements

**Comment by AmoleR** [comment]
@vEnhance I was thinking of doing a notification model to also help with #9 where you just store the email information in that? What's your thoughts on this?

**Comment by vEnhance** [comment]
> @vEnhance I was thinking of doing a notification model to also help with #9 where you just store the email information in that? What's your thoughts on this?

I guess that would work too

**Comment by vEnhance** [comment]
Going to unassign myself for now since #9 might end up closing it anyways

**Comment by vEnhance** [comment]
Finished in 9ebe42508732e8e718347b00f657d46d04f1b2cd.
