### ISSUE TITLE
Unit Unlock

### ISSUE THREAD

**Issue by issacmeng** [vEnhance/otis-web#48]
Maybe the choice 'next unit to unlock' can be shown in the submission review page 
https://otis.evanchen.cc/dash/psetxxx
later, so that we do not choose an unit more than once when we submit more than one unit before the previous ones are checked off. I think that the code for preventing double unlocking can be implemented, if possible.

**Comment by vEnhance** [comment]
Finished in 9ebe42508732e8e718347b00f657d46d04f1b2cd.
