### ISSUE TITLE
Incorporate unit artwork into catalog

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#51]
Probably just an optional image field to add

**Comment by Psi25Omega** [comment]
i wanna try implementing this
would you like the image to correspond to the `UnitGroup` model or the `Unit` model?

**Comment by vEnhance** [comment]
I was thinking `UnitGroup`

**Comment by vEnhance** [comment]
Closing for now since it doesn't look like I'll have much time for art anyways.
