### ISSUE TITLE
Clickable emojis in meters

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/otis-web#71]
People seem to have a hard time finding the "View Stats" button and then
clicking through to the details of each of their stats. So maybe we should make
each of the emojis clickable, having it show the detailed page and automatically
expand the relevant menu

**Comment by Psi25Omega** [comment]
A question…As an example, if a person is on the portal’s home page and clicks on the spades icon, should he be redirected to the `stats’ page with the details of the spades thingy or is this supposed to happen in the home page per se

**Comment by vEnhance** [comment]
> As an example, if a person is on the portal’s home page and clicks on the spades icon, should he be redirected to the stats page with the details of the spades thingy

Yes, that's the hope.

**Comment by AmoleR** [comment]
Probably can be done by giving each a unique `id` (say one of them is `some-category-instead`) and redirecting to `https://www.otis.evanchen.cc/this-is-not-the-url-but-i-forgot-it#some-category-instead`.

**Comment by vEnhance** [comment]
Anone want to take a stab at this? I'm currently being held somewhere against my will so I don't ave my usual work rig to to do as much as I like to do.

**Comment by TheCoolDinosuar** [comment]
I think I'll try, but I'm not sure how long it'll take for me to get everything figured out.
