### ISSUE TITLE
ARCH Problem Identifier Case Sensitivity

### ISSUE THREAD

**Issue by issacmeng** [vEnhance/otis-web#76]
When I accidentally add a new problem with a lowercase identifier, it does not correspond to the right problem in the wiki page, and the right problem cannot be created after the lowercase one is created.  Maybe it is better to make it not case sensitive.

**Comment by vEnhance** [comment]
Seems like the correct fix is to put a `RegexValidator` on the ARCH model PUID field to require all letters to be alphanumeric uppercase.

This should be pretty straightforward I think --- likely could be done in two lines of code (not counting the stray migration that would result). So I'll put this up for bounty first, if anyone wants to take this as a learning opportunity.

**Comment by vEnhance** [comment]
Finished in 02991204703d278180f67eff33b8674b67c1df5b.
